#!/bin/bash


testcase=$1

res=~/Dropbox/Stuff1819/proooject/Project/code/src/results
cd ~/Dropbox/Stuff1819/proooject/Project/code/src


./_build/default/runFromFile.exe "$testcase-pho" &

psrecord $(pgrep runFromFile.exe) --plot "$res/pho.png" --log "$res/pho.txt"
