#!/bin/bash


iter=$1

log="$HOME/Dropbox/Stuff1819/proooject/Project/code/src/scripts/logrev"

bigtime=0

respho=()

rm $log
touch $log


echo "$iter"

for i in $(seq 1 $iter)
do
echo "$i"

echo "my compiler" | tee -a $log
cd ~/Dropbox/Stuff1819/proooject/Project/code/src
# OCAMLRUNPARAM="h=1k,s=1k"
# export OCAMLRUNPARAM="h=1k,s=1k"


# OCAMLRUNPARAM="h=1G,s=1G"
export OCAMLRUNPARAM="h=300k,s=300k"

dune exec ./writeToFile.exe "reverse-pho" >> $log


dune build ./runFromFile.exe >> $log

if [[ $bigtime -eq 1  ]]
then
/usr/bin/time --verbose ./_build/default/runFromFile.exe "reverse-pho" |& tee -a $log
else
me=$(/usr/bin/time -f '%U' ./_build/default/runFromFile.exe "reverse-pho" |& tee -a $log)
echo $me
respho+=("$me")
fi

# /usr/bin/time -f '%U'



done

echo
echo pho
echo "${respho[*]}"

notify-send --urgency=critical "its done :)"

beep
