#!/bin/bash


testcase=$1



echo "my compiler"
cd ~/Dropbox/Stuff1819/proooject/Project/code/src
# OCAMLRUNPARAM="h=3G,s=3G"
export OCAMLRUNPARAM="h=3G,s=3G"

dune exec ./writeToFile.exe "$testcase-pho"

# runFromFile.exe
dune build ./runFromFile.exe



cd ~/Dropbox/Stuff1819/proooject/Project/code/src/bench



TRAILSZ=30720 CSTRSZ=3072 GLOBALSZ=8192 LOCALSZ=409600 gplc --no-top-level "$testcase-gnu.pl"




swipl -G100g -T20g -L5g -o "swi_executables/$testcase.plexe" -g goal -c "$testcase-swi.txt"




notify-send --urgency=critical "its done :)"

beep
